# Generated by Django 4.2.1 on 2023-06-22 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0005_trip_businessplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPlacePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('id_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_place', to='watchlist_app.businessplace')),
            ],
        ),
    ]
