# Generated by Django 4.2.1 on 2023-06-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_businessplacepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessplace',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='businessplacepicture',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
